title: GitHub training
author: GitHub User btorano
email: btorano@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning GitHub YAY

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
them: minima
